In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
df_sal = pd.read_csv('Salary Data.csv')
df_sal.head()

Age  Gender Education Level          Job Title  Years of Experience  \
0  32.0    Male      Bachelor's  Software Engineer                  5.0   
1  28.0  Female        Master's       Data Analyst                  3.0   
2  45.0    Male             PhD     Senior Manager                 15.0   
3  36.0  Female      Bachelor's    Sales Associate                  7.0   
4  52.0    Male        Master's           Director                 20.0   

     Salary  
0   90000.0  
1   65000.0  
2  150000.0  
3   60000.0  
4  200000.0

In [ ]:
df_sal.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 375 entries, 0 to 374
Data columns (total 6 columns):
 #   Column               Non-Null Count  Dtype  
---  ------               --------------  -----  
 0   Age                  373 non-null    float64
 1   Gender               373 non-null    object 
 2   Education Level      373 non-null    object 
 3   Job Title            373 non-null    object 
 4   Years of Experience  373 non-null    float64
 5   Salary               373 non-null    float64
dtypes: float64(3), object(3)
memory usage: 17.7+ KB


In [ ]:
df_sal.shape

(375, 6)

In [ ]:
df_sal.columns

Index(['Age', 'Gender', 'Education Level', 'Job Title', 'Years of Experience',
       'Salary'],
      dtype='object')

In [ ]:
df_sal.dtypes

Age                    float64
Gender                  object
Education Level         object
Job Title               object
Years of Experience    float64
Salary                 float64
dtype: object

In [ ]:
df_sal.describe()

Age  Years of Experience         Salary
count  373.000000           373.000000     373.000000
mean    37.431635            10.030831  100577.345845
std      7.069073             6.557007   48240.013482
min     23.000000             0.000000     350.000000
25%     31.000000             4.000000   55000.000000
50%     36.000000             9.000000   95000.000000
75%     44.000000            15.000000  140000.000000
max     53.000000            25.000000  250000.000000

In [ ]:
df_sal.isnull().sum()

Age                    2
Gender                 2
Education Level        2
Job Title              2
Years of Experience    2
Salary                 2
dtype: int64

Since the missing values here is only about 2 cell
we recommend to drop it.

In [ ]:
df_sal.dropna(inplace=True)

In [ ]:
df_sal.isnull().sum()

Age                    0
Gender                 0
Education Level        0
Job Title              0
Years of Experience    0
Salary                 0
dtype: int64

In [ ]:
df_sal['Age'].unique()

array([32., 28., 45., 36., 52., 29., 42., 31., 26., 38., 48., 35., 40.,
       27., 44., 33., 39., 25., 51., 34., 47., 30., 41., 37., 24., 43.,
       50., 46., 49., 23., 53.])

In [ ]:
df_sal['Education Level'].unique()

array(["Bachelor's", "Master's", 'PhD'], dtype=object)

In [ ]:
df_sal['Job Title'].unique()

array(['Software Engineer', 'Data Analyst', 'Senior Manager',
       'Sales Associate', 'Director', 'Marketing Analyst',
       'Product Manager', 'Sales Manager', 'Marketing Coordinator',
       'Senior Scientist', 'Software Developer', 'HR Manager',
       'Financial Analyst', 'Project Manager', 'Customer Service Rep',
       'Operations Manager', 'Marketing Manager', 'Senior Engineer',
       'Data Entry Clerk', 'Sales Director', 'Business Analyst',
       'VP of Operations', 'IT Support', 'Recruiter', 'Financial Manager',
       'Social Media Specialist', 'Software Manager', 'Junior Developer',
       'Senior Consultant', 'Product Designer', 'CEO', 'Accountant',
       'Data Scientist', 'Marketing Specialist', 'Technical Writer',
       'HR Generalist', 'Project Engineer', 'Customer Success Rep',
       'Sales Executive', 'UX Designer', 'Operations Director',
       'Network Engineer', 'Administrative Assistant',
       'Strategy Consultant', 'Copywriter', 'Account Manager',
      

In [ ]:
df_sal['Years of Experience'].unique()

array([ 5. ,  3. , 15. ,  7. , 20. ,  2. , 12. ,  4. ,  1. , 10. , 18. ,
        6. , 14. , 16. ,  0. , 22. , 19. ,  9. , 13. , 11. , 25. , 21. ,
        8. , 17. , 23. , 24. ,  0.5,  1.5])

In [ ]:
df_sal['Salary'].unique()

array([ 90000.,  65000., 150000.,  60000., 200000.,  55000., 120000.,
        80000.,  45000., 110000.,  75000., 140000., 130000.,  40000.,
       125000., 115000.,  35000., 180000., 190000.,  50000., 250000.,
       170000., 160000.,  85000.,  95000., 105000.,  70000., 100000.,
        30000., 135000., 220000., 175000., 185000., 145000., 155000.,
          350.])

In [ ]:
#one_hot_encoded_data = pd.get_dummies(df_sal, columns = ['Education Level', 'Job Title'])
#one_hot_encoded_data.head()
#df_sal = one_hot_encoded_data
#df_sal.head()

In [ ]:
from sklearn.preprocessing import LabelEncoder
label_encoder  = LabelEncoder
df_sal['Education Level'] = LabelEncoder().fit_transform(df_sal['Education Level'])
df_sal['Job Title'] = LabelEncoder().fit_transform(df_sal['Job Title'])
df_sal['Gender'] = LabelEncoder().fit_transform(df_sal['Gender'])
df_sal.head()

Age  Gender  Education Level  Job Title  Years of Experience    Salary
0  32.0       1                0        159                  5.0   90000.0
1  28.0       0                1         17                  3.0   65000.0
2  45.0       1                2        130                 15.0  150000.0
3  36.0       0                0        101                  7.0   60000.0
4  52.0       1                1         22                 20.0  200000.0

In [ ]:
x = df_sal.drop('Salary', axis=1)
y = df_sal['Salary']

In [ ]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

In [ ]:
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(298, 5)
(75, 5)
(298,)
(75,)


In [ ]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()
model.fit(x_train, y_train)

LinearRegression()

In [ ]:
y_pred = model.predict(x_test)
y_pred

array([167633.68695158,  93362.33215371, 130879.62380038,  84293.36442107,
       161044.59433795, 159610.94787507, 157000.39505879, 104784.30551165,
        57465.48625109, 101175.03451504, 142482.4450066 , 159352.51378797,
        37768.65650053,  89223.07711416, 128351.50002112,  57465.48625109,
        69484.90832554,  48721.19405008,  79606.57259308,  98260.82737399,
       130410.96947762, 107945.05479157, 164848.27420428,  61322.28998856,
        84293.36442107,  48897.53543308, 173331.57805348,  44351.87749589,
       120285.16237824, 146397.2536315 ,  44218.98186682, 126080.77232505,
        54954.57717977, 152512.26204751,  91172.88837559,  17482.61459055,
       183262.63824557,  50889.17487793, 157008.19157712,  58775.47175403,
        44486.54350791,  93846.47239797, 167011.51764444, 163268.61863972,
        42790.47464318, 156531.74073603, 123117.09499936,  54312.9752329 ,
        49204.89084627,  35285.67655361, 152888.62740023,  80549.1691895 ,
       127271.13258475, 1

In [ ]:
y_test

329    180000.0
33      65000.0
15     125000.0
316     80000.0
57     140000.0
         ...   
94      75000.0
196     90000.0
313     60000.0
294    140000.0
349    110000.0
Name: Salary, Length: 75, dtype: float64

In [ ]:
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score, mean_absolute_percentage_error

In [ ]:
print('Mean squared error: ', mean_squared_error(y_test, y_pred))
print('Mean absolute error: ', mean_absolute_error(y_test, y_pred))
print('R2 score: ', r2_score(y_test, y_pred))
print('Mean absolute percentage error: ', mean_absolute_percentage_error(y_test, y_pred))

Mean squared error:  249075656.42722148
Mean absolute error:  10928.921486231397
R2 score:  0.8961138207821864
Mean absolute percentage error:  0.11433405286896857


In [ ]:
lr = LinearRegression()
Lr = lr.fit(x_train, y_train)
Lr.score(x_test, y_test)

0.8961138207821864

In [ ]:
print(y_test.head())

print(y_pred[:5])

y_pred

329    180000.0
33      65000.0
15     125000.0
316     80000.0
57     140000.0
Name: Salary, dtype: float64
[167633.68695158  93362.33215371 130879.62380038  84293.36442107
 161044.59433795]


array([167633.68695158,  93362.33215371, 130879.62380038,  84293.36442107,
       161044.59433795, 159610.94787507, 157000.39505879, 104784.30551165,
        57465.48625109, 101175.03451504, 142482.4450066 , 159352.51378797,
        37768.65650053,  89223.07711416, 128351.50002112,  57465.48625109,
        69484.90832554,  48721.19405008,  79606.57259308,  98260.82737399,
       130410.96947762, 107945.05479157, 164848.27420428,  61322.28998856,
        84293.36442107,  48897.53543308, 173331.57805348,  44351.87749589,
       120285.16237824, 146397.2536315 ,  44218.98186682, 126080.77232505,
        54954.57717977, 152512.26204751,  91172.88837559,  17482.61459055,
       183262.63824557,  50889.17487793, 157008.19157712,  58775.47175403,
        44486.54350791,  93846.47239797, 167011.51764444, 163268.61863972,
        42790.47464318, 156531.74073603, 123117.09499936,  54312.9752329 ,
        49204.89084627,  35285.67655361, 152888.62740023,  80549.1691895 ,
       127271.13258475, 1

In [91]:
import plotly.express as px
from plotly.offline import iplot

df_plot = pd.DataFrame({
    'Actual_Salary': y_test,
    'Predicted_Salary': y_pred,
    'error': y_test - y_pred  # Calculate the error
})

# Create the scatter plot
fig = px.scatter(
    df_plot,
    x='Actual_Salary',
    y='Predicted_Salary',
    color='error',
    opacity=0.8,
    title='Predicted Vs. Actual',
    template='plotly_dark',
    trendline='ols'
)


fig.update_layout(
    title = {
        "font" :{
            "size" : 28,
            "family" : "tahoma"
        }
    }
)
iplot(fig)